#!/bin/env bash

# Host status
function return_host {
    if [[ -z $1 ]]; then
        echo -n 'target was not specified'
        exit 1
    else
        echo -n $1
    fi
}

function host_status {
    if ping -c 1 -W 0.5 $1 > /dev/null 2>&1; [[ $? -eq 0 ]]; then
        echo -n "UP" 
    else
        echo -n "DOWN"
    fi
}


# Print results
function print_results {
    echo "CURRENT REMOTE_HOST: $(return_host $remote_host)"
    echo "REMOTE_HOST STATUS: $(host_status $remote_host)"
	echo
    echo "CURRENT TARGET: $(return_host $target)"
    echo "TARGET STATUS: $(host_status $target)"
	echo
    echo "CURRENT TARGET1: $(return_host $target1)"
    echo "TARGET1 STATUS: $(host_status $target1)"
    exit 0
}

print_results
