#!/bin/env bash

uid=$(id | grep -oP '(?<=uid=)[0-9]+')

if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
then
	case $uid in
		"0") sed -i "136s/.*/export target1=$1/" ~/.bashrc; sed -i "136s/.*/export target1=$1/" /home/*/.bashrc;;
		*) sed -i "136s/.*/export target1=$1/" ~/.bashrc;;
	esac
else
    echo "You should specify IPv4 address"
    exit 1
fi
