#!/bin/env bash

function return_ip {
    if [[ -z $1 ]]; then
        echo -n "N/A"
        exit 1
    else
        echo -n $1
    fi
}

function ip_status {
	if ping -c 1 -W 0.5 $1 > /dev/null 2>&1; [[ $? -eq 0 ]]; then
        echo -n "UP" 
    else
        echo -n "DOWN"
    fi
}

function update_eth_ip {
	eth_ip=$(ip -f inet addr show eth0 2>/dev/null | grep -Po 'inet \K[\d.]+')
	if [[ $eth_ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
	then
		case $EUID in
            "0") sed -i "6s/.*/export eth_ip=$eth_ip/" ~/.pentest_values; sed -i "6s/.*/export eth_ip=$eth_ip/" /home/*/.pentest_values;;
            *) sed -i "6s/.*/export eth_ip=$eth_ip/" ~/.pentest_values;;
		esac
	fi
}

function update_eth_gateway {
	eth_gateway=$(netstat -rn 2>/dev/null | grep eth0 | awk '{print $2}' | head -1 | tr -d "\n")
	if [[ $eth_gateway =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
	then
		case $EUID in
            "0") sed -i "7s/.*/export eth_gateway=$eth_gateway/" ~/.pentest_values; sed -i "7s/.*/export eth_gateway=$eth_gateway/" /home/*/.pentest_values;;
            *) sed -i "7s/.*/export eth_gateway=$eth_gateway/" ~/.pentest_values;;
		esac
	fi
}

function update_tun0_ip {
	tun0_ip=$(ip -f inet addr show tun0 2>/dev/null | grep -Po 'inet \K[\d.]+')
	if [[ $tun0_ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
	then
		case $EUID in
            "0") sed -i "9s/.*/export tun0_ip=$tun0_ip/" ~/.pentest_values; sed -i "9s/.*/export tun0_ip=$tun0_ip/" /home/*/.pentest_values;;
            *) sed -i "9s/.*/export tun0_ip=$tun0_ip/" ~/.pentest_values;;
		esac
	fi
}

function update_tun0_gateway {
	tun0_gateway=$(netstat -rn 2>/dev/null | grep tun0 | awk '{print $2}' | head -1 | tr -d "\n")
	if [[ $tun0_gateway =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
	then
		case $EUID in
			"0") sed -i "10s/.*/export tun0_gateway=$tun0_gateway/" ~/.pentest_values; sed -i "10s/.*/export tun0_gateway=$tun0_gateway/" /home/*/.pentest_values;;
			*) sed -i "10s/.*/export tun0_gateway=$tun0_gateway/" ~/.pentest_values;;
		esac
	fi
}

function update_tun1_ip {
	tun1_ip=$(ip -f inet addr show tun1 2>/dev/null | grep -Po 'inet \K[\dr]+' )
	if [[ $tun1_ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
	then
		case $EUID in
            "0") sed -i "12s/.*/export tun1_ip=$tun1_ip/" ~/.pentest_values; sed -i "12s/.*/export tun1_ip=$tun1_ip/" /home/*/.pentest_values;;
            *) sed -i "12s/.*/export tun1_ip=$tun1_ip/" ~/.pentest_values;;
		esac
	fi
}

function update_tun1_gateway {
	tun1_gateway=$(netstat -rn 2>/dev/null | grep tun1 2>/dev/null | awk '{print $2}' | head -1 | tr -d "\n" 2>/dev/null)
	if [[ $tun1_gateway =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
	then
		case $EUID in
			"0") sed -i "13s/.*/export tun1_gateway=$tun1_gateway/" ~/.pentest_values; sed -i "13s/.*/export tun1_gateway=$tun1_gateway/" /home/*/.pentest_values;;
			*) sed -i "13s/.*/export tun1_gateway=$tun1_gateway/" ~/.pentest_values;;
		esac
	fi
}

function get_options {
    echo -e "\$eth_ip: \033[1m$(return_ip $eth_ip)\033[0m"
    echo -e "\$eth_gateway: \033[1m$(return_ip $eth_gateway)\033[0m"
    echo
    echo -e "\$tun0_ip: \033[1m$(return_ip $tun0_ip)\033[0m"
    echo -e "\$tun0_gateway: \033[1m$(return_ip $tun0_gateway)\033[0m"
    echo -e "\$tun1_ip: \033[1m$(return_ip $tun1_ip)\033[0m"
    echo -e "\$tun1_gateway: \033[1m$(return_ip $tun1_gateway)\033[0m"
    echo
    echo "Targets:"
    echo -en "\$target: \033[1m$(return_ip $target)\033[0m  status: "; echo -e "\033[1m$(ip_status $target)\033[0m"
    echo -en "\$target1: \033[1m$(return_ip $target1)\033[0m  status: "; echo -e "\033[1m$(ip_status $target1)\033[0m"
    echo -en "\$target2: \033[1m$(return_ip $target2)\033[0m  status: "; echo -e "\033[1m$(ip_status $target2)\033[0m"
    echo -en "\$remote_host: \033[1m$(return_ip $remote_host)\033[0m  status: "; echo -e "\033[1m$(ip_status $remote_host)\033[0m"
    exit 0
}

update_eth_ip;
update_eth_gateway;

update_tun0_ip;
update_tun0_gateway;

update_tun1_ip;
update_tun1_gateway;

get_options;
