#!/bin/env bash


function return_host {
    if [[ -z $1 ]]; then
        echo -n 'target was not specified'
        exit 1
    else
        echo -n $1
    fi
}


function host_status {
	if ping -c 1 -W 0.5 $1 > /dev/null 2>&1; [[ $? -eq 0 ]]; then
        echo -n "UP" 
    else
        echo -n "DOWN"
    fi
}


function update_gateway {
	uid=$(id | grep -oP '(?<=uid=)[0-9]+')

	gateway=$(ip r | grep default | grep -Eo "[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}" | head -n1 | tr -d '\n')
	if [[ $gateway =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
	then
		case $gateway in
			"0") sed -i "137s/.*/export gateway=$gateway/" ~/.bashrc; sed -i "137s/.*/export gateway=$gateway/" /home/*/.bashrc;;
			*) sed -i "137s/.*/export gateway=$gateway/" ~/.bashrc;;
		esac
	else
		echo "You should specify IPv4 address"
		exit 1
	fi
}


function get_options {
    echo -e "current gateway: \033[1m$(return_host $gateway)\033[0m"
    echo -en "target: \033[1m$(return_host $target)\033[0m status: "; echo -e "\033[1m$(host_status $target)\033[0m"
    echo -en "target1: \033[1m$(return_host $target1)\033[0m status: "; echo -e "\033[1m$(host_status $target1)\033[0m"
    echo -en "remote_host: \033[1m$(return_host $remote_host)\033[0m status: "; echo -e "\033[1m$(host_status $remote_host)\033[0m"
    exit 0
}

update_gateway;

get_options;
