#!/bin/env bash

xrandr --auto

xrandr --output DVI-D-1 --rotate left
xrandr --output DP-1 --rotate left

xrandr --output DVI-D-1 --left-of HDMI-1
xrandr --output DP-1 --left-of DVI-D-1

xrandr --auto
