#!/bin/env bash

repos_to_backup=(
    '/home/modernpacifist/Documents/github-repositories/System-backups'
    '/home/modernpacifist/Documents/github-repositories/dotenv'
    '/home/modernpacifist/Documents/github-repositories/bash-pentesting-tools'
    '/home/modernpacifist/Documents/github-repositories/python3-practice'
    '/home/modernpacifist/Documents/github-repositories/reverse-engineering'
    '/home/modernpacifist/Documents/github-repositories/c-language-practice'
    )

for repo_dir in ${repos_to_backup[@]};
do 
    cd $repo_dir
    git add -A && git commit -m "$(date "+%d/%m/%Y-%T") automated backup" && git push
done
