#!/bin/env bash
orig_display=$(echo -n $DISPLAY)
DISPLAY=:0
declare -a devices=('AlpsPS/2 ALPS DualPoint TouchPad' 'AlpsPS/2 ALPS DualPoint Stick' 'AT Translated Set 2 keyboard' '6' '9' 'Sleep Button')
for device in "${devices[@]}";
do
	xinput disable "$device"
done
xdotool mousemove 0 1080
export DISPLAY=$orig_display
