#!/bin/env bash
while :
do
    read line 
    playing=$(playerctl metadata --format '{{artist}}- {{title}}' | sed 's/\-\ Topic//')
    block="{\"full_text\":\"$playing\"}"
    echo "${line/\[\{/\[$block,\{}" || exit 1
done
