#!/bin/env bash
if [[ -z $1 ]]; 
then
    echo 'Help with:'
    echo 'hydra/gobuster/nc/git'
fi

if [[ $1 == hydra ]]; 
then
    ssh_bruteforce='hydra [-l|-L] <login> [-p|-P] <pwd> -s <port> <host> ssh -vV'
    http_basicauth='hydra [-l|-L] <login> [-p|-P] <pwd> -s <port> -f <host> http[s]-[post|get]-form /<login-page>'
    http_auth='hydra [-l|-L] <login> [-p|-P] <pwd> -s <port> -f <host> http[s]-[post|get]-form /<login-page>'

    echo "1) $ssh_bruteforce"
    echo "2) $http_basicauth"
    echo "3) $http_auth"

    read -t 30 -p 'state your choice: ' choice
    case $choice in
        1) echo -n $ssh_bruteforce | xclip -selection c;;
        2) echo -n $http_basicauth | xclip -selection c;;
        3) echo -n $http_auth | xclip -selection c;;
        *) echo 'nothing was chosen';;
    esac
fi

if [[ $1 == gobuster ]]; 
then
    a='gobuster dir -u <target> -w <wordlist> -t 150'
    echo "1) $a"
    
    read -t 30 -p 'state your choice: ' choice
    case $choice in
        1) echo -n $a | xclip -selection c;;
        *) echo 'nothing was chosen';;
    esac
fi

if [[ $1 == nc ]]; 
then
    nc_intercept='nc -nlvp <port>'

    echo "1) $nc_intercept"

    read -t 30 -p 'state your choice: ' choice
    case $choice in
        1) echo -n $nc_intercept | xclip -selection c;;
        *) echo 'nothing was chosen';;
    esac
fi

if [[ $1 == git ]];
then
    git_rm_remote='git rm -r --cached <folder_name>'

    echo "Remove object from remote repo, not local"
    echo "1) $git_rm_remote"

    read -t 30 -p 'state your choice: ' choice
    case $choice in
        1) echo -n $git_rm_remote | xclip -selection c;;
        *) echo 'nothing was chosen';;
    esac
fi
