#!/bin/env bash
if [[ $1 =~ ^[0-9]{1,5}$ ]];
then
	case $EUID in
		"0") sed -i "19s/.*/export port1=$1/" ~/.pentest_values; sed -i "19s/.*/export port1=$1/" /home/*/.pentest_values;;
		*) sed -i "19s/.*/export port1=$1/" ~/.pentest_values;;
	esac
else
    echo "You should specify correct port number"
    exit 1
fi
