#!/bin/env python3.9
from argparse import ArgumentParser


def get_args():
    parser = ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("-m", "--message", dest="message", action="store", help="specify single message")
    group.add_argument("-c", "--ciphertext", nargs="+", dest="ciphertext", type=list,
                       help="specify ciphertext")
    return parser.parse_args()


def bruteforce_string(ciphertext: str, offset: int):
    res = []
    for i in ciphertext:
        if (i.isupper()):
            res.append(chr((ord(i) + offset-65) % 26 + 65))
        elif (i.islower()):
            res.append(chr((ord(i) + offset-97) % 26 + 97))
        else:
            res.append(i)
    return ''.join(res)


def bf_single_msg(message):
    for offset in range(0, 26):
        print(bruteforce_string(message, offset))


def bf_ciphertext(ciphertext):
    for offset in range(0, 26):
        for string in ciphertext:
            print(bruteforce_string(string, offset), end=" ")
        print()


def main():
    args = get_args()

    if args.message:
        bf_single_msg(args.message)
    elif args.ciphertext:
        bf_ciphertext(args.ciphertext)


if __name__ == "__main__":
    main()
