#!/bin/env bash
if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]];
then
	case $EUID in
		"0") sed -i "1s/.*/export target=$1/" ~/.pentest_values; sed -i "1s/.*/export target=$1/" /home/*/.pentest_values;;
		*) sed -i "1s/.*/export target=$1/" ~/.pentest_values;;
	esac
else
    echo "You should specify IPv4 address"
    exit 1
fi
