filetype off
syntax enable
set tabstop=4
set shiftwidth=4
set smarttab
set smartindent
set expandtab
set number
set mouse=
set nocompatible              
set statusline=%<%f\ %h%m%r%{kite#statusline()}%=%-14.(%l,%c%V%)\ %P
set laststatus=2
set completeopt+=menuone
set completeopt+=noinsert
set completeopt-=preview
set timeoutlen=1000
set ttimeoutlen=0
set hidden
set ignorecase
set nowrap

"----Vundle settings----
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

"----Code/project navigation----
Plugin 'jeffkreeftmeijer/vim-numbertoggle'
Plugin 'terryma/vim-multiple-cursors'
Plugin 'AutoClose'
Plugin 'klen/python-mode'
Plugin 'preservim/nerdcommenter'

call vundle#end()
filetype plugin indent on

if filereadable("/etc/vim/vimrc.local")
	source /etc/vim/vimrc.local
endif

let g:pymode_python = 'python3'
let g:kite_tab_complete=1
