set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'valloric/youcompleteme'

Plugin 'Command-T'

Plugin 'easymotion/vim-easymotion'

map <F2> :set hlsearch!<CR> * #

call vundle#end()            " required
filetype plugin indent on    " required

syntax enable
set shiftwidth=4
set noswapfile
set number
set tabstop=4
set expandtab

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

let g:EasyMotion_leader_key ='<Tab>'
