set nocompatible              
filetype on

set rtp+=~/.vim/bundle/Vundle.vim

call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'easymotion/vim-easymotion'

Plugin 'terryma/vim-multiple-cursors'

Plugin 'rip-rip/clang_complete'

Plugin 'octol/vim-cpp-enhanced-highlight'

Plugin 'chun-yang/auto-pairs'

Plugin 'scrooloose/nerdcommenter'

Plugin 'tpope/vim-surround'

Plugin 'jeffkreeftmeijer/vim-numbertoggle'

Plugin 'davidhalter/jedi-vim'
call vundle#end()            

syntax enable
set shiftwidth=4
set softtabstop=4
set noswapfile
set number
set tabstop=4
set noexpandtab

if filereadable("/etc/vim/vimrc.local")
	source /etc/vim/vimrc.local
endif

let g:EasyMotion_leader_key = '<Tab>'

let g:clang_library_path='/usr/lib/llvm-8/lib/libclang-8.so'

